name: Hello Action
on:
  workflow_dispatch:
jobs:
  build:
    name: Deploy2
    runs-on: self-hosted
    steps:
    
      # Checkout code
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - run: sleep 2
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: 1 Docker Action ashishkurmi/hello-action
        uses: ashishkurmi/hello-action@main
        env:
          SLEEPINSECONDS: 5
